### ISSUE TITLE
Download step 2c

### ISSUE THREAD

**Issue by Spaceman918** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#1]
Hello,

first of all I really enjoyed working with your OpenCV project - thank you for sharing your knowledge.

As I wanted to dig in deeper e.g. with cards overlapping each other my guess is that this approach will fit my needs better. I cannot find the files you are referring to in step 2c, I am too early or is there any problems getting these files downloaded?

tia
Spaceman918

**Comment by EdjeElectronics** [comment]
Hey, thanks for your interest in this tutorial! As you saw, all the files are now added. Keep an eye out for my YouTube video that walks through the tutorial!
