### ISSUE TITLE
Advice please

### ISSUE THREAD

**Issue by nujcharee** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#109]
Im a python newbie - managed to follow your tutorial and it worked on my PC (windows)! Thank you so much. However I would like to be able to put button for the end user to start the webcam and stop the webcam... Im not sure if python can do this? Thank you for your advice.

**Comment by EdjeElectronics** [comment]
Hi @nujcharee , this is definitely possible! However, it will take some work. I recommend using OpenCV, which can display a window with a simple button, and detect when a user clicks on the button. Then, you can start the webcam when OpenCV detects that the button is clicked. Here's a tutorial that shows how to handle mouse events in OpenCV: https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_mouse_handling/py_mouse_handling.html#mouse-handling
