### ISSUE TITLE
when i'm run training 

### ISSUE THREAD

**Issue by ektavyas** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#119]
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\ektav\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\model_builder.py", line 31, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\ektav\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ImportError: No module named 'nets'

**Comment by ektavyas** [comment]
it's not working

**Comment by mzh1993** [comment]
I created a virtual environment tensorflow1 according to the tutorial, and then encountered a lot of errors, just like you. Then I created it directly in the Anaconda boot environment and it succeeded.

**Comment by ektavyas** [comment]
anaconda boot environment is already set during installation..
but it's not working

**Comment by mzh1993** [comment]
Is it working properly in your boot environment? If not, checking your CPU, tensorflow 1.6.0 or later does not support old CPU.Try to install the tensorflow 1.5.0.

**Comment by ektavyas** [comment]
Successfully installed setuptools-39.1.0 tensorflow-1.10.0

**Comment by sauronpy** [comment]
its seems that the pre-trained model haven't copied in object-detection folder.

download a pre-trained model in model zoo page and extract it in object-detection folder.

cheers...

**Comment by ektavyas** [comment]
it's done and when i 'm configure my training data it's run properly but
when i am jump on next step i.e when i am run

python train.py --logtostderr --train_dir=training/
--pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

this command it show error
