### ISSUE TITLE
Object_detection_webcam.py error

### ISSUE THREAD

**Issue by NikolayStarikov** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#13]
Dear colleagues,

I'm getting an error running Object_detection_webcam.py on both python2 and python3. 
Could you please advice what can be a solution?

RESTART: /home/nikolay/tensorflow1/models/research/object_detection/Object_detection_webcam.py 

Traceback (most recent call last):
  File "/home/nikolay/tensorflow1/models/research/object_detection/Object_detection_webcam.py", line 103, in <module>
    feed_dict={image_tensor: frame_expanded})
  File "/home/nikolay/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/nikolay/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1106, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/nikolay/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by EdjeElectronics** [comment]
Hello, this error means the "frame_expanded" variable is empty, which usually means the webcam somehow didn't initialize properly. It's most likely an issue with the webcam. Please re-open this issue if you find the problem is caused by the code.

**Comment by eillenlun** [comment]
@NikolayStarikov @EdjeElectronics I am experiencing the same problem. My camera will turn on when I run the program. Opening means it starts working, but I reported the same error.
![125](https://user-images.githubusercontent.com/42166064/46186546-d1694e80-c311-11e8-91c2-3111bc72ff74.PNG)

**Comment by eillenlun** [comment]
My camera's light is on, but I get an error.

**Comment by mjasonong** [comment]
same error here. anyone knows how to solve this problem?

**Comment by cookiekhai** [comment]
![tensorflow error](https://user-images.githubusercontent.com/46528493/51260045-5921b880-19e8-11e9-8873-2d273ccf551d.PNG)

**Comment by cookiekhai** [comment]
i got this error when i try to run it on the webcam. does that mean i dint install the open cv?
