### ISSUE TITLE
Labels.txt

### ISSUE THREAD

**Issue by vishal-prgmr** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#139]
How do I create a labels.txt ? From the test and train image sets we create two csv files and a labels.pbtxt file. But how to generate a labels.txt file?

**Comment by Burgomehl** [comment]
take a texteditor and write the labels you have learned to your net into it, line by line. Then save it as labels.txt
