### ISSUE TITLE
Saved the detected video

### ISSUE THREAD

**Issue by ThomasLiu1021** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#145]
Hi there. My detection works great and I want to saved the detected video to local not just display it.
Is there any modifications I can do to save this video?

I am using the Object_detection_video.py file

Thx

**Comment by EdjeElectronics** [comment]
Hi @ThomasLiu1021 , please see this link for how to save a video using OpenCV: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html
