### ISSUE TITLE
error while training the data

### ISSUE THREAD

**Issue by srivathsav98** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#158]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape mismatch in tuple component 18. Expected [1,?,?,3], got [1,1,504,378,3]
         [[Node: batch/padding_fifo_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_STRING, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT, ..., DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/padding_fifo_queue, IteratorGetNext, Shape_3, IteratorGetNext:1, Shape_5, RandomHorizontalFlip/cond_1/Merge, Shape_4, IteratorGetNext:3, Shape_10, IteratorGetNext:4, Shape_7, IteratorGetNext:5, Shape_8, IteratorGetNext:6, Shape_11, IteratorGetNext:7, Shape_6, IteratorGetNext:8, Shape_9, ExpandDims_1, Shape, IteratorGetNext:10, Shape_3, IteratorGetNext:11, Shape_3, IteratorGetNext:12, Shape_12, IteratorGetNext:13, Shape_3)]]

**Comment by buddhikadissanayake** [comment]
have you found a solution for this issue?

**Comment by SangSonyratt** [comment]
have you found a solution for this issue?
