### ISSUE TITLE
To decrease FPS

### ISSUE THREAD

**Issue by RajMalar** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#16]
Can anyone suggest a method to decrease the frame per second.......My FPS is 29 ...I want to convert it to 1FPS

**Comment by RajMalar** [comment]
Exactly where I have to give that condition ...I tried giving it to main loop but cant able to see any change...can u help me with this plzz...thanks

**Comment by RajMalar** [comment]
On object_detection_video.py......

**Comment by alhparsa** [comment]
Modify the following line:
`    if cv2.waitKey(delayedTime) == ord('q'):
        break
`
to:
`    if cv2.waitKey(1000) == ord('q'):
        break
`
if you want 1FPS

**Comment by RajMalar** [comment]
thanks:)

**Comment by EdjeElectronics** [comment]
Thanks alhparsa for helping out!
