### ISSUE TITLE
label_map.pbtxt file ; No such file directory

### ISSUE THREAD

**Issue by nerellasureshkumar7** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#162]
Hi while i tried to train the object detector it's saying no "label_map.prbtxt file". The file exist in the object detction/training folder. I have checked the paths in config file. I'm using Ubuntu 16.04, GeForce GTX 1050 Ti/PCIe/SSE2. Tensorflow version is 1.5. please help me

**Comment by Burgomehl** [comment]
Isn't it "label_map.pbtxt file" without the "r".
At which path is your labelmap and what is the content of your config file?

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w
