### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by godofping** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#164]
(tensorflow1) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 110, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 101, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 75, in create_tf_example
    classes_text.append(row['class'].encode('utf8'))
AttributeError: 'int' object has no attribute 'encode'

**Comment by Burgomehl** [comment]
https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/159#issue-365432072

**Comment by bemmy2005** [comment]
The solution on this link helps me to solve the issue: https://stackoverflow.com/questions/34301687/attributeerror-int-object-has-no-attribute-encode

**Comment by mkbx01** [comment]
find this code:
classes_text.append(row['class'].encode('utf8'))
classes.append(class_text_to_int(row['class']))

change 'class' to 'str'

classes_text.append(row['str'].encode('utf8'))
classes.append(class_text_to_int(row['str']))

**Comment by RD121** [comment]
> (tensorflow1) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
> Traceback (most recent call last):
> File "generate_tfrecord.py", line 110, in
> tf.app.run()
> File "C:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> _sys.exit(main(argv))
> File "generate_tfrecord.py", line 101, in main
> tf_example = create_tf_example(group, path)
> File "generate_tfrecord.py", line 75, in create_tf_example
> classes_text.append(row['class'].encode('utf8'))
> AttributeError: 'int' object has no attribute 'encode'

bro have got the solution to this problem

**Comment by bipulneupane** [comment]
find this code:
classes_text.append(row['class'].encode('utf8'))
classes.append(class_text_to_int(row['class']))

change these line to:

classes_text.append(str(row['class']).encode('utf8'))
classes.append(class_text_to_int(row['class']))

**Comment by erolgerceker** [comment]
> find this code:
> classes_text.append(row['class'].encode('utf8'))
> classes.append(class_text_to_int(row['class']))
> 
> change 'class' to 'str'
> 
> classes_text.append(row['str'].encode('utf8'))
> classes.append(class_text_to_int(row['str']))

i doesnt work

**Comment by BharathKR** [comment]
find this code:
classes_text.append(row['class'].encode('utf8'))
classes.append(class_text_to_int(row['class']))

and change it to

classes_text.append(str(row['class']).encode('utf8'))
classes.append(class_text_to_int(str(row['class'])))

**Comment by sanaz-rasti** [comment]
> find this code:
> classes_text.append(row['class'].encode('utf8'))
> classes.append(class_text_to_int(row['class']))
> 
> change these line to:
> 
> classes_text.append(str(row['class']).encode('utf8'))
> classes.append(class_text_to_int(row['class']))

This worked for me, THANK YOU!
