### ISSUE TITLE
setting the path 

### ISSUE THREAD

**Issue by rahulkumar07** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#17]
I think you missed% in PYTHONPATH for the line- (tensorflow1) C:\> set PATH=%PATH%;PYTHONPATH

it should be (tensorflow1) C:\> set PATH=%PATH%;%PYTHONPATH%

**Comment by EdjeElectronics** [comment]
Thanks, someone had pointed this out on my YouTube video too. It turns it still works because you don't actually have to set PATH, you only need to set PYTHONPATH. I updated the tutorial to remove the instructions regarding PATH.

**Comment by Elites2017** [comment]
I have a problem in step 4 generating the data. Who can help me please?

(tensflow) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 110, in <module>
    tf.app.run()
  File "C:\Users\David-Up\Anaconda3\envs\tensflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 101, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 90, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\David-Up\Anaconda3\envs\tensflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

![image](https://user-images.githubusercontent.com/35799396/42648543-74ccc700-8631-11e8-80fd-1cd6018d265e.png)


Thanks in advance guys

**Comment by mohamadian123-Sadegh** [comment]
I also have this issue.

**Comment by mohamadian123-Sadegh** [comment]
I solved it. you should do as follow:
in generate_tf_records change None in line 45 to :

    else:
        return 0
