### ISSUE TITLE
Why not using SSD Inception v2 or v3 instead of Faster RCNN? 

### ISSUE THREAD

**Issue by anonym24** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#179]
As I understand Google made SSD Inception and I guess it should be the best for Tensorflow, the fastest

**Comment by anonym24** [comment]
cause it's hard to train it with legacy script `train.py`, it's better use `model_train.py` - https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/184

**Comment by zyb1996** [comment]
in this project,how to change codes?when i try the familiar method like faster rcnn,i have a problem:IndexError: list index out of range.
