### ISSUE TITLE
How do I load checkpoint files directly without exporting as frozen graph

### ISSUE THREAD

**Issue by kulkarnivishal** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#189]
Hi, 

Thank you for the repo. I am facing trouble restoring checkpoint file. Even though I use the trained .meta to load the graph and try to restore from checkpoint files. I don't wish to export frozen graph, but run prediction directly on the checkpoint files (by loading the model using kept file). Can it be done? 

Best,
Vishal

**Comment by thebeyonder001** [comment]
Were you able to do the inference?
I too am stuck at not being able to loading the model
