### ISSUE TITLE
Object_detection_image.py isn't suitable for MobileNet SSD model?

### ISSUE THREAD

**Issue by anonym24** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#198]
when I test trained MobileNet SSD model using Object_detection_image.py I get weird results: it detects boxes everywhere

tough it works fine with  Faster-RCNN-Inception-V2 model 

or is just script isn't suitable for MobileNet SSD model?

**Comment by EdjeElectronics** [comment]
The large number of boxes is most likely due to the MobileNet SSD model's lower accuracy. The script works the same regardless of which type of model is used. Did you train it on your own dataset? It may be that the dataset has too few pictures or doesn't have clear enough images of the object.
