### ISSUE TITLE
This tutorial

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#199]
I want to tell the author of this, that this is the best tutorial I have ever seen. Not just on this topic, even not just about computers.
This has to be the new standard of precision.

If you didn't notice or have doubts, I am dead serious about this.

**Comment by EdjeElectronics** [comment]
Thanks buddy, I really appreciate it! I got frustrated with other ambiguous tutorials, and it inspired me to make my own with very clear instructions.
