### ISSUE TITLE
request for LICENSE

### ISSUE THREAD

**Issue by MareoRaft** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#213]
Could you please put a `LICENSE` file on your repository?  I would recommend the MIT license for your use case, since it allows other people to use your repo while protecting you.

Without a license, your repo is protected under US copyright law (see https://choosealicense.com/no-permission/) and I cannot legally use it, AFAIK.

Thank you kindly,
Matthew

**Comment by EdjeElectronics** [comment]
Added the Apache 2.0 license since that is what the TensorFlow GitHub repository uses. Cheers!
