### ISSUE TITLE
No image shown at the end of running object_detection_tutorial.ipynb

### ISSUE THREAD

**Issue by srinibujjay** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#232]
After running the file no image of dog and the other one found , and no error also generated out of the file

**Comment by longjie1986** [comment]
I have met this issue too,  I have find a way in google, please comment out the matplotlib importing in the research/object_detection/visualization_utils.py as a temporary fix, 
#import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
#import matplotlib.pyplot as plt  # pylint: disable=g-import-not-at-top

hope it will be fix official soon...

**Comment by srinibujjay** [comment]
Perfectly working after commenting out !!
I Luv the python community for this kind of supports

**Comment by GigsyKami** [comment]
@srinibujjay @longjie1986 heyy where should run that code? i face the same problem...

**Comment by ganeshx-o** [comment]
perfectly working!!u saved my day

**Comment by stanleywym** [comment]
> I have met this issue too, I have find a way in google, please comment out the matplotlib importing in the research/object_detection/visualization_utils.py as a temporary fix,
> #import matplotlib; matplotlib.use('Agg') # pylint: disable=multiple-statements
> #import matplotlib.pyplot as plt # pylint: disable=g-import-not-at-top
> 
> hope it will be fix official soon...

Thanks! It works. Minor correction though. The path should be `research/object_detection/utils/visualization_utils.py`

**Comment by Rashed-BUET** [comment]
> I have met this issue too, I have find a way in google, please comment out the matplotlib importing in the research/object_detection/visualization_utils.py as a temporary fix,
> #import matplotlib; matplotlib.use('Agg') # pylint: disable=multiple-statements
> #import matplotlib.pyplot as plt # pylint: disable=g-import-not-at-top
> 
> hope it will be fix official soon...

Thanks a lot. It works.

**Comment by maheshagodekere** [comment]
Yes, this fix worked for me too on MAC!!!
Thanks.

**Comment by Marwen-Bhj** [comment]
Commented out the lines, downgraded matplotlib from 3.1.1 to 3.0.1, inserted `%matplotlib inline` and still facing the same issue.

**Comment by mehmetsoylu** [comment]
> @srinibujjay @longjie1986 heyy where should run that code? i face the same problem...

You have to get in your C: file and you should find the visualization_utils.py file in there after that open visualization_utils.py and make the below lines comment.

 #import matplotlib; matplotlib.use('Agg') # pylint: disable=multiple-statements
#import matplotlib.pyplot as plt # pylint: disable=g-import-not-at-top

**Comment by Ridzzz0Alam** [comment]
Amazing fix thanx a lot
