### ISSUE TITLE
How to increase video FPS in detecting object with video file 

### ISSUE THREAD

**Issue by srinibujjay** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#237]
Hi 

Object_detection_video.py file is streaming video very slowly, how to increase the speed of FPS

**Comment by cocopambag** [comment]
What ar the computer specs?

**Comment by srinibujjay** [comment]
HP pavilion intel i5,windows10,8GBDDR4,1 TBSSHD,NVIDIA GEFORCE 940MX(2GB)

not sure due to system spec or tensorflow-gpu ??

**Comment by srinibujjay** [comment]
Hopefully this is due to the selected model in tensorflow

**Comment by cocopambag** [comment]
Do you use faster_rcnn_v2_coco ??

**Comment by srinibujjay** [comment]
i used faster_rcnn_inception_v2_pets.config
