### ISSUE TITLE
How can you print the detected objects in real time?

### ISSUE THREAD

**Issue by Twikkxx** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#241]
I want to print the detected object in my real time images, how can I do that or is that possible?

**Comment by cocopambag** [comment]
Do you use faster-rcnn-v2-coco ?

**Comment by Twikkxx** [comment]
I use the ssdlite mobilenet v2, I'am using it on my raspberry pi

**Comment by shiba17** [comment]
So do you found a way to display the detected objects?
