### ISSUE TITLE
error in sizeChecker.py for licence plate recognition

### ISSUE THREAD

**Issue by Crystaldias** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#242]
I am running this code for license plate recognition. I have labeled the number plates (there is only 1 class) of the car images. While running the python file sizeChecker.py, I am getting the following error. It would be a great help if this issue could be resolved.   
![image](https://user-images.githubusercontent.com/38811836/53342426-e8998000-3933-11e9-97c0-a344bdb9a5f9.png)

**Comment by EdjeElectronics** [comment]
Hi @Crystaldias , you can skip the sizeChecker.py step, and it should still work. I am removing the instructions to run the sizeChecker.py script.

**Comment by ozcan-durak** [comment]
@Crystaldias Have you been able to achieve dedection on licence plate recognition with Faster R-CNN ?

**Comment by Crystaldias** [comment]
Yes, i have. Thanks a lot.
