### ISSUE TITLE
How to display the time for the model to detect objects, for image input?

### ISSUE THREAD

**Issue by shiba17** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#270]
Aside from displaying the image with the boundary boxes, confidence score and object class, I would like to display the time taken for the model to detect the object. The output will be shown in the terminal. This is for image input.

**Comment by EdjeElectronics** [comment]
Hi @shiba17 , you can use the cv2.getTickCount() and cv2.getTickFrequency() functions to determine the elapsed time between any two points in code. Here is a good example: https://docs.opencv.org/3.3.1/dc/d71/tutorial_py_optimization.html
