### ISSUE TITLE
import error no module named pandas

### ISSUE THREAD

**Issue by aswinr22** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#275]
i have installed pandas and still no module named pandas why??

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w

**Comment by execptionerror** [comment]
All Possible solution added [[Solved] ImportError: No module named pandas](https://flutterq.com/importerror-no-module-named-pandas/)
