### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by mihuzz** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#292]
### I cant run Training, maybe someone can help me please
``(sdk) D:\Lesson8\models\research\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:

https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.
Traceback (most recent call last):
File "legacy/train.py", line 51, in 
from object_detection.builders import model_builder
File "D:\Lesson8\models\research\object_detection\builders\model_builder.py", line 27, in 
from object_detection.builders import post_processing_builder
File "D:\Lesson8\models\research\object_detection\builders\post_processing_builder.py", line 22, in 
from object_detection.protos import post_processing_pb2
File "D:\Lesson8\models\research\object_detection\protos\post_processing_pb2.py", line 16, in 
from object_detection.protos import calibration_pb2 as object__detection_dot_protos_dot_calibration__pb2
ImportError: cannot import name 'calibration_pb2'`

**Comment by swayam69** [comment]
Check the step 2 from the Readme file. It is different from the video. You would have missed the protos part
