### ISSUE TITLE
command after object detection

### ISSUE THREAD

**Issue by RecepFatih** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#293]
Hello. I want to run a command after object detection. how can I do that? for example, 'start recording the screen after the desired object has been detected'. how do I add this command? can you help me?

**Comment by swayam69** [comment]
Find the code for recording the screen and add it to webcam.py or image.py whichever file you are using

**Comment by swayam69** [comment]
Find the code for recording the screen and add it to webcam.py or image.py whichever file you are using

**Comment by RecepFatih** [comment]
but I don't want him to record it all the time, I just want him to find it when he detects it. how do I ensure this?

**Comment by RecepFatih** [comment]
> Find the code for recording the screen and add it to webcam.py or image.py whichever file you are using

but I don't want him to record it all the time, I just want him to find it when he detects it. how do I ensure this?

**Comment by swayam69** [comment]
Put it after the detection code

**Comment by EdjeElectronics** [comment]
Hi @RecepFatih , take a look at my Pet Detector video and code, it shows you how to trigger actions after certain objects have been detected.

Video: https://www.youtube.com/watch?v=gGqVNuYol6o
Code: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/blob/master/Pet_detector.py
