### ISSUE TITLE
slowly on video

### ISSUE THREAD

**Issue by mops1112** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#296]
Why does it slowly view on a video file? the video slowly moves next frame it looks like slow motion, cars and people gradually moved.
note: I use a faster_rcnn_inception_v2_pets for training on RTX 2080 x 2 and image size are 600*500

**Comment by EdjeElectronics** [comment]
It takes a long time to load each frame from the video file and pass it through the neural network. It works better with a real-time feed from a webcam.
