### ISSUE TITLE
error when training data in the example

### ISSUE THREAD

**Issue by qjqjqjj** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#30]
Hi,

Firstly, thanks for your detailed explanation. However, when I tried to train the model I had the following error which I am not sure where is it:

`(tensorflow1) D:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From D:\tensorflow1\models\research\object_detection\trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:tensorflow:From D:\tensorflow1\models\research\object_detection\core\box_predictor.py:396: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\tensorflow1\models\research\object_detection\core\losses.py:316: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\tensorflow1\models\research\object_detection\trainer.py", line 255, in train
    train_config.optimizer)
  File "D:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "D:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 109, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "D:\tensorflow1\models\research\object_detection\utils\learning_schedules.py", line 156, in manual_stepping
    raise ValueError('First step cannot be zero.')
ValueError: First step cannot be zero.`

Thanks!

**Comment by S-aiueo32** [comment]
When I tested this work with the cards dataset, it worked well.
So I tried to train the network with my own data on another computer.
I think generating records was done successfully, however I've had the same error.
Considering from the error message, It seems to be caused by `train_config` in `faster_rcnn_inception_v2_pets.config` we've created.
Fixing about the learning rate, I think it will work.
I'm sorry but I don't have any more ideas about it.

**Comment by S-aiueo32** [comment]
I found the answer in https://github.com/tensorflow/models/issues/3794.

**Comment by EdjeElectronics** [comment]
Thanks S-aiueo32 for posting the link to the solution!

**Comment by mekaci89** [comment]
2018 solution with new format. Uncomment these two lines in the learning_schedules.py and you start to generate steps to train your custom images. I check the 2017 tutorials but the way of writing code in 2018 has changed at some parts so you stuck at every steps with old tutorials.

if boundaries and boundaries[0] == 0:
    raise ValueError('First step cannot be zero.')
