### ISSUE TITLE
How to remove the confidence level in a detected image?

### ISSUE THREAD

**Issue by kamal0803** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#303]
![photo](https://user-images.githubusercontent.com/42574558/60250977-49869400-98e5-11e9-9bb0-b3b6f23489fd.jpg)

I want to remove the 99% written on the image. Please help

**Comment by QuickLearner171998** [comment]
vis_util.visualize_boxes_and_labels_on_image_array(
    image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.60,
    **skip_scores=True**)

In vis_util.visualize_boxes_and_labels_on_image_array in Object_detection_Image.py add skip_scores =True.
For more options to play with u can check this function defined in visualization_utils.py file in utils directory.

**Comment by kamal0803** [comment]
Thanks a lot..

**Comment by EdjeElectronics** [comment]
Thank you for helping out @QuickLearner171998!
