### ISSUE TITLE
Finding co-ordinates of the rectangle in which object is detected

### ISSUE THREAD

**Issue by kamal0803** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#305]
My image is detecting object..But I want to find the co-ordinates of the rectangle formed..Please help

**Comment by QuickLearner171998** [comment]
In object_detection_image.py file : 
(boxes, scores, classes, num) = sess.run(
    [detection_boxes, detection_scores, detection_classes, num_detections],
    feed_dict={image_tensor: image_expanded})
boxes gives the coordinates of the bounding boxes i this order: ymin, xmin, ymax, xmax
boxes is np array of shape (1,max_detections,4).

**Comment by kamal0803** [comment]
Thank you!

**Comment by EdjeElectronics** [comment]
You can see an example of how to do this in my Pet Detector video and code:

Video: https://www.youtube.com/watch?v=gGqVNuYol6o
Code: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/blob/master/Pet_detector.py
