### ISSUE TITLE
retrieving coordinates of identified objects 

### ISSUE THREAD

**Issue by chinya07** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#326]
I want the identified objects' images at runtime. I want to process on those identified objects further. Please help me to get those coordinates of identified objects. How can I get those ? I am getting huge multidimentional array from 'boxes'. How can I normalize it or convert it into coordinates so that I can get those images?

**Comment by EdjeElectronics** [comment]
Hi @chinya07 , please watch my Pet Detector video, which shows how to find the coordinates of detected objects. It also explains how detection results are stored in the 'boxes', 'scores', 'classes', and 'num' arrays.
https://www.youtube.com/watch?v=gGqVNuYol6o

**Comment by kamal0803** [comment]
Refer this, https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/305

**Comment by chinya07** [comment]
Thank you! @EdjeElectronics
