### ISSUE TITLE
Train.py (FeatureExtractor is not avaiable)

### ISSUE THREAD

**Issue by mihuzz** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#332]

**Comment by MarkusKurzmann** [comment]
I'm currently facing the same issue with lots and lots of `" ... is not available in checkpoint"`-messages followed by messages like these:
 `I0821 00:34:15.101966 22036 supervisor.py:1099] global_step/sec: 0`
`I0821 00:36:13.737035 22036 supervisor.py:1099] global_step/sec: 0`
`I0821 00:38:13.738087 22036 supervisor.py:1099] global_step/sec: 0`
`I0821 00:40:13.737649 22036 supervisor.py:1099] global_step/sec: 0`
`I0821 00:42:13.737709 22036 supervisor.py:1099] global_step/sec: 0`
... but without any further progress in learning.
 Is there any possible solution for this yet?
