### ISSUE TITLE
faster_rcnn_inception_v2_coco_2018_01_28 vs faster_rcnn_inception_v2_pets

### ISSUE THREAD

**Issue by AeroWRX** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#343]
During the instructions step to finally train the model...

Why are we using faster_rcnn_inception_v2_pets.config when we copied over the faster_rcnn_inception_v2_coco_2018_01_28 model? Shouldn't we be using faster_rcnn_inception_v2_coco...config instead?

**Comment by EdjeElectronics** [comment]
Hi @AeroWRX , if you inspect both the .config files, you'll find they are almost exactly identical. The only differences are the num_classes (which we are changing anyway) and some minor differences in the train and test input configuration. Either file will work.
