### ISSUE TITLE
python3: can't open file 'train.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mikolaj24** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#345]
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

train.py not exist

**Comment by aidoshacks** [comment]
where are you running train.py from? Also did you copy the file over from /object_detection/legacy folder?

**Comment by mikolaj24** [comment]
can You read readme?
6. Run the Training

UPDATE 9/26/18: As of version 1.9[...]

python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

and look at repository train.py not exist

**Comment by aidoshacks** [comment]
"UPDATE 9/26/18: As of version 1.9, TensorFlow has deprecated the "train.py" file and replaced it with "model_main.py" file. I haven't been able to get model_main.py to work correctly yet (I run in to errors related to pycocotools). Fortunately, the train.py file is still available in the /object_detection/legacy folder. Simply move train.py from /object_detection/legacy into the /object_detection folder and then continue following the steps below."

This has been a well known issue for many and is clearly highlighted in the Readme. 

Can you read readme?

**Comment by mikolaj24** [comment]
this are not clear

**Comment by sachinroy123** [comment]
raining': [Errno 2] No such file or directory

**Comment by ali97hz** [comment]
as he said @aidoshacks , noone reads the readme , just replace "python train.py" to "python model_main.py"

**Comment by SnehaVardhan09** [comment]
If this problem is on colab
try changing from
=>drive.mount('/content/gdrive')
     %cd '/content/gdrive/'
to particular path where the train.py is present
=> drive.mount('content/gdrive')
      %cd '/content/gdrive/My Drive/models/research/object_detection/'

**Comment by esraaraoof** [comment]
please help me
I tried to make yolov5 in google colab 
https://colab.research.google.com/github/roboflow-ai/yolov5-custom-training-tutorial/blob/main/yolov5-custom-training.ipynb#scrollTo=eaFNnxLJbq4J

when I write

!python legacy/train.py --img 416 --batch 16 --epochs 150 --data /content/gdrive/My Drive/dataset/data.yaml --weights yolov5s.pt --cache

it makes error

python3: can't open file 'legacy/train.py': [Errno 2] No such file or directory

**Comment by abdelkarim86** [comment]
![image](https://user-images.githubusercontent.com/54859798/177204149-ece47270-df3f-4d16-8ed2-9fa3a6dbb7af.png)
hi,  I'm trying tosolve this problem on google colab but i don't find solution please help me

**Comment by deftttttt** [comment]
> ![image](https://user-images.githubusercontent.com/54859798/177204149-ece47270-df3f-4d16-8ed2-9fa3a6dbb7af.png) hi, I'm trying tosolve this problem on google colab but i don't find solution please help me

you forget install requirments,at the top
