### ISSUE TITLE
jupyter note book doesn't out put any result when in step 2g

### ISSUE THREAD

**Issue by macgihan** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#346]
i have working environment of  tensor flow following this great guide and im stucked at level 2g 
could anyone help

**Comment by macgihan** [comment]
[object_detection_tutorial.pdf](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/files/3554157/object_detection_tutorial.pdf)

**Comment by EdjeElectronics** [comment]
Hi @macgihan , please see the note at the end of Step 2g:

**Note: If you run the full Jupyter Notebook without getting any errors, but the labeled pictures still don't appear, try this: go in to object_detection/utils/visualization_utils.py and comment out the import statements around lines 29 and 30 that include matplotlib. Then, try re-running the Jupyter notebook.**

**Comment by macgihan** [comment]
Thank you so much
