### ISSUE TITLE
Do Image XML <Path> Improper Linking Matter?

### ISSUE THREAD

**Issue by AeroWRX** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#351]
All my <PATH> locations in the XML files are not set to \object_detection\images\train or \object_detection\images\test directories. Does <PATH> location in the XML record matter or is Tensorflow API smart enough to use whatever is inside the Images folders?

**Comment by aidoshacks** [comment]
I believe the linking does matter. I haven't been able to successfully train a model otherwise.
