### ISSUE TITLE
can we use this in android?

### ISSUE THREAD

**Issue by ferdinan97** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#356]
so i read a post :https://medium.com/@daniel.fleury02/tutorial-real-time-android-object-detection-of-pneumonia-chest-x-ray-opacities-using-ssd-63b14813627
can this model implemented like that one ?

**Comment by HaFred** [comment]
I am sure it can, try using tensorflow lite

**Comment by EdjeElectronics** [comment]
I am working on a guide showing how to train and export a TensorFlow Lite model, and then how to use it on Android or on the Raspberry Pi. Will be coming out next month!
