### ISSUE TITLE
TypeError:TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by kriz232121** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#368]
Traceback (most recent call last):
  File "C:\Users\Tensorflow\models\research\object_detection\Object_detection_image.py", line 96, in <module>
    (boxes, scores, classes, num) = sess.run([detection_boxes, detection_scores, detection_classes, num_detections],feed_dict={image_tensor: image_expanded})
  File "D:\Users\Cristian\Miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\Users\Cristian\Miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1142, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "D:\Users\Cristian\Miniconda3\envs\tensorflow1\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
i have problems with object_detection_image please healp me

**Comment by EdjeElectronics** [comment]
That errors means it's trying to pass an empty variable into the detection model, which means that the code failed to load the image. Make sure you are using the correct image path.

**Comment by kushu9999** [comment]
i got this type of error anyone knows how to solve please tell me i searching about it's solution lasst 3 days , i applied all things but it didn't solved

TypeError Traceback (most recent call last)
in ()
83 (boxes, scores, classes, num) = sess.run(
84 [detection_boxes, detection_scores, detection_classes, num_detections],
---> 85 feed_dict={image_tensor: frame_expanded})
86
87 # Draw the results of the detection (aka 'visulaize the results')

2 frames
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
83
84 """
---> 85 return array(a, dtype, copy=False, order=order)
86
87

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by anik511** [comment]
getting this error in colab


TypeError                                 Traceback (most recent call last)
<ipython-input-22-20bd75232e66> in <module>()
     90 (boxes, scores, classes, num) = sess.run(
     91     [detection_boxes, detection_scores, detection_classes, num_detections],
---> 92     feed_dict={image_tensor: image_expanded})
     93 # Draw the results of the detection (aka 'visulaize the results')
     94 

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1147             feed_handles[subfeed_t] = subfeed_val
   1148           else:
-> 1149             np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
   1150 
   1151           if (not is_tensor_handle_feed and

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ghumman3131** [comment]
I got the same error but once I updated TensorFlow to version 2.2.0 the issue get resolved.

**Comment by kushu9999** [comment]
Okay thanks, I'll check it out
