### ISSUE TITLE
Bounding Box Not showing

### ISSUE THREAD

**Issue by Passionatecricketer** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#372]
I am training on my own dataset to detect objects with 11 classes.
Everything is working fine but even after training for more than 40000 steps the image is not showing any bounding box or accuracy score around the part to be detected.
I am testing on images present in test directory and when I run object_detection_image.py only original image is showing without the predictions.

Can please someone help me?

**Comment by azayz** [comment]
Hey can you write your solution ? I'm facing similar issue

**Comment by Passionatecricketer** [comment]
Hi @azayz 
Actually I found out that it was some issue with the software I was using for annotating images. It was storing wrong coordinates for the boxes that's why score was zero in every case
One solution can be you can check the score of the detected boxes...maybe they are not crossing the threshold value

**Comment by azayz** [comment]
Thanks for the response I found out what my issue was, my classes were 0 and 1 and it turns out that class 0 is reserved for background I changed the classes to 1 and 2 and now it works.

**Comment by idabble31** [comment]
Hi, i'm facing the same issue. Could you please elaborate the steps on how to fix this problem?

**Comment by idabble31** [comment]
Hi @azayz @Passionatecricketer , I'm facing the same issue. Could you please elaborate the steps on how to fix this problem? I'm training my own datasets with 1 classes of objects. I've trained it until 50000 steps and the detection still doesn't show up even though the training process is working fine.

**Comment by Annieliaquat** [comment]
@Passionatecricketer @azayz @idabble31 Please someone help  me too with this issue.. I am training my model in colab. Everything works fine my images are trained but no bounding box is shown on my image. Please do help me

**Comment by Annieliaquat** [comment]
> Hi @azayz @Passionatecricketer , I'm facing the same issue. Could you please elaborate the steps on how to fix this problem? I'm training my own datasets with 1 classes of objects. I've trained it until 50000 steps and the detection still doesn't show up even though the training process is working fine.

Please help me too. I am doing my detection in colab but no bounding box is not showing.
