### ISSUE TITLE
Failed to find any matching files for .../model.ckpt

### ISSUE THREAD

**Issue by biakko2688** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#377]
So I started trying to set this image classifier up last night, and I eventually ran into this error:

tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt

I tried creating a file called model.ckpt in both the faster_rcnn folder and the training folder, but a different error popped up:

Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?

The tutorial doesn't mention creating a model.ckpt file, and since it didn't work I'm guessing something else is wrong. I'm on tensorflow version 1.15 with tensorflow-gpu 1.15 as well. I'm using the old model from early 2018 in the tutorial because I figured I don't need a new one for my purposes. I can add any other information needed, but I'm very new to tensorflow and don't really know what is usually needed to solve these problems. Any help is appreciated!

**Comment by iCounterBOX** [comment]
I also got this model.ckpt  error message during my (painful) deployment...
it should look like this:

![image](https://user-images.githubusercontent.com/37293282/67362111-a3812880-f56a-11e9-99f7-22363af30e82.png)

i also reproduced the sdje-solution for my OWN pictures to classify...
1. its essential to be crystal clear in matching versions(TF, CUDA, cuDNN,...) 
2. in case  restart training etc to clean SOME folders in the right manner...i documented this all here in my REPO:
https://github.com/iCounterBOX/TensorFlow_CarOccupancyDetector_V2

for me 1.12 was working

**Comment by biakko2688** [comment]
Thank you for the reply! My problem may be caused by incompatibility issues then. Do you know which versions of CUDA and cuDNN you used? And should all of the files you showed be created automatically? At the moment my faster_rcnn folder only contains the faster_rcnn TAR file, which I don't even see in yours. Maybe that has something to do with it?
