### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Ricftrw** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#381]
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 32, in <module>
    slim_example_decoder = tf.contrib.slim.tfexample_decoder
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by Nightrain** [comment]
Check your version of tensorflow.  Tensorflow 2.0 does not support contrib anymore.  I am stuck as well, I just rolled back to an older version of tensorflow

**Comment by JulianOrteil** [comment]
TF2.0 will no longer contain the 'contrib' module. Install any 1.x version of TF like the following:
pip install tensorflow==1.15.0
(1.15.0 contains both the GPU and CPU version in the same pip distribution)
