### ISSUE TITLE
Failed to install pycocotools on Windows8 with VS2012 installed

### ISSUE THREAD

**Issue by elektronika-ba** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#393]
Hi Evan,
This is not directly related to your tutorial, but it fails on my PC and I am wondering if you may help out.
Following your instructions in "2g. Test TensorFlow setup to verify it works" it fails on step

> !pip install pycocotools

When I run the command outside the jyputer I get error saying:

> cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'

including bunch of others.

Then in your tutorial you mention that you also had issues with pycocotools, so I am wondering if I can ignore this error (comment it out in yupiter file) and proceed without it?

edit: There is no bash on my Windows :-) so these fail also...

Thanks

**Comment by elektronika-ba** [comment]
Update:
Simply skipping the command that does pip install pycocotools does the job. Also where it fails because of lack of bash is also not a problem.

Bottomline, tutorial works if you skip the pycocotools part, and ignore bash errors.

**Comment by Nyceane** [comment]
pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
