### ISSUE TITLE
Issues while Generating TFrecords

### ISSUE THREAD

**Issue by luisc30** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#394]
Hello:

I am Trying to generate tfrecord file with tensorflow 2.0, at the first I have generated correctly the files, but when I am trying generate them again, python console show an error below:

``
Traceback (most recent call last):
  File "generate_tfrecordv2.py", line 106, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\LUIS\AppData\Roaming\Python\Python37\site-packages\tensorflow_c
ore\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\LUIS\AppData\Roaming\Python\Python37\site-packages\absl\app.py"
, line 299, in run
    _run_main(main, args)
  File "C:\Users\LUIS\AppData\Roaming\Python\Python37\site-packages\absl\app.py"
, line 250, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecordv2.py", line 95, in main
    grouped = split(examples, 'filename')
  File "generate_tfrecordv2.py", line 45, in split
    gb = df.groupby(group)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line
 7632, in groupby
    observed=observed, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.p
y", line 2110, in groupby
    return klass(obj, by, **kwds)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.p
y", line 360, in __init__
    mutated=self.mutated)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\groupby\grouper.p
y", line 578, in _get_grouper
    raise KeyError(gpr)
KeyError: 'filename'
``
CSV file content is just like that:

filename;width;height;class;xmin;ymin;xmax;ymax
19219.jpg;800;600;person;49;49;377;559
19219.jpg;800;600;person;431;131;644;592

Can you tell me what is the error? the command that I did use is this: 

python generate_tfrecord.py --csv_input=train_labels.csv --image_dir=train --output_path=train.record

An example for the xml is below (I changed < and > for # just for this post):

`#annotation#

  #folder#data_modified#/folder#
  #filename#1_245#/filename#
  #path#C:\material\dataset\test\1_245.jpg#/path#
  #source#
    #database#Unknown#/database#
  #/source#
  #size#
    #width#800#/width#
    #height#600#/height#
    #depth#3#/depth#
  #/size#
  #segmented#0#/segmented#
  #object#
    #name#person#/name#
    #pose#Unspecified#/pose#
    #truncated#0#/truncated#
    #difficult#0#/difficult#
    #bndbox#
      #xmin#279#/xmin#
      #ymin#116#/ymin#
      #xmax#423#/xmax#
      #ymax#415#/ymax#
    #/bndbox#
  #/object#
#/annotation#`

**Comment by JulianOrteil** [comment]
Add '.jpg' to '1_245' in the <filename> header.

It should look like this:
<filename>1_245.jpg</filename>

**Comment by luisc30** [comment]
@JulianOrteil Thank you so much, it works.

**Comment by hoanglvdev** [comment]
![image](https://user-images.githubusercontent.com/73802582/113504506-b327dd80-9562-11eb-847a-7860e5221e0f.png)
can you help me solve this error
