### ISSUE TITLE
object recognition is not working correctly

### ISSUE THREAD

**Issue by PortScanner** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#420]
I have followed the instructions very carefully. Nevertheless, my training models don't work. The object - lastly a heron - is recognized, but countless herons are recognized again and again in all pictures in which there is definitely no heron. What am I doing wrong?

**Comment by ilkot** [comment]
how many training & test images did you use? deep learning models may need large numbers to learn well

**Comment by PortScanner** [comment]
Thank you for your prompt reply.
in the example "heron" I used 206 train and 52 test pictures.
However, only 10 pictures are displayed in the tensorboard. is that correct? Otherwise the training machine runs completely normal and everything seems ok. some parameter seems wrong.

**Comment by PortScanner** [comment]
yes, now it works. I ignored a little thing. sorry for the unnecessary question. anyway thanks to Ilkot, you are right, I still need more pictures.

**Comment by Petros626** [comment]
@PortScanner hey

how did you solve that, what was wron in the generate_tf_records?
