### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

### ISSUE THREAD

**Issue by koravat** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#438]
AttributeError                            Traceback (most recent call last)
<ipython-input-23-31f3625391de> in <module>
      1 model_name = 'faster_rcnn_inception_v2_coco_2018_01_28'
----> 2 detection_model = load_model(model_name)

<ipython-input-16-886ee8813c9d> in load_model(model_name)
      9   model_dir = pathlib.Path(model_dir)/"saved_model"
     10 
---> 11   model = tf.compat.v2.saved_model.load(str(model_dir))
     12   model = model.signatures['serving_default']
     13 

AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

**Comment by Ahmadzia307** [comment]
Can you share which version you are using Tf, cuda and cudnn

**Comment by Ahmadzia307** [comment]
If you are following the tutorial and using it's model then tensorflow-gpu 1.5,cuda 9.0 and cudnn7.0.* are the correct version to use.

**Comment by koravat** [comment]
thank
