### ISSUE TITLE
Object_detection_image.py  |  cuDNN launch failure : input shape ([1,300,400,64])

### ISSUE THREAD

**Issue by Ahmadzia307** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#440]
I am using Tensorflow 1.5
python 3.5.4
Cuda 9.0
When I run the Object_detection_image.py I am having the attached image ERROR. I have tried the 
  config = tf.ConfigProto()
  config.gpu_options.allow_growth = True
 sess = tf.Session( config=config ,graph=detection_graph)
But It does not solve the Issue.
![Issue Tensorflow](https://user-images.githubusercontent.com/24617277/73867223-1dae9200-4868-11ea-82e0-e1f4d8727603.png)

**Comment by Ahmadzia307** [comment]
@HiCraigChen  Can you help me this, Please?

**Comment by Ahmadzia307** [comment]
It was the Cudnn Issue
I was using 7600 version instead of 7000 version

**Comment by Gaturae** [comment]
Have you solved this Issue? and how?@Ahmadzia307

**Comment by Ahmadzia307** [comment]
@Gaturae I have solved the Issue by Changing my CUDNN version to 7.0.*
