### ISSUE TITLE
How to cite you?

### ISSUE THREAD

**Issue by SciarrinoQauntumLab** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#45]
Hello! I'd like to thank you a lot for such a precise guide! I largely used it for my research project and I would cite you the way you prefer. May you help me? Thank you.

**Comment by EdjeElectronics** [comment]
Hi, thank you very much for considering to cite me in your project! You can use:

Evan Juras, _How to train a TensorFlow Object Detection Classifier for multiple object detection on Windows_, 2018, GitHub repository, https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

I'm interested to hear about your project. If you wind up writing a paper or publish some other sort of media (presentation, website, video, etc.) please let me know! You can contact me over Twitter or through my email posted on my YouTube channel at https://www.youtube.com/channel/UCLuS8eZl3_nKKq85gPS62lQ/about . Good luck with your research!
