### ISSUE TITLE
"N/A" on some results of testing

### ISSUE THREAD

**Issue by WeitlerT** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#46]
Hi there, we have been training our model based off of different articles of clothing (shirts, pants, jackets, etc). It identifies them correctly in most cases, but in some cases it will identify a piece of clothing and label it with an N/A. Any solution or explanation for this? It is identifying the different articles of clothing as separate entities but does not label them correctly. I have added an example screenshot [example image](https://i.imgur.com/1jNjrqb.jpg)

**Comment by EdjeElectronics** [comment]
Make sure you have assigned the correct number of classes for the NUM_CLASSES variable on line 48 in the Object_detection_webcam.py (or image or video). Also, make sure you changed num_classes on line 9 of the faster_rcnn_inception_v2_pets.config file too.

If you didn't have the correct setting for num_classes in the .config file before training, you might need to re-train the whole model after changing it.

**Comment by WeitlerT** [comment]
This fixed it thanks! Forgot to change num_classes in the testing files.
