### ISSUE TITLE
What version of tf and Models work ?

### ISSUE THREAD

**Issue by mustafaazzurr** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#460]
Hello, it was 2 days and i was trying to get it work but every time new error 
could someone please give me exactly what version works and on which repository commed and the models version too because i feel lost

**Comment by kushallokesh** [comment]
Hello mustafaazzurr,

I tried with tf 2.0 it failed, downgraded to 1.15 and trying now and models reppo 1.13.0. Have a feeling this will work. Will keep you posed. Do you want to work together to set this up?

**Comment by kushallokesh** [comment]
Also look at issue #383

**Comment by mustafaazzurr** [comment]
> Hello mustafaazzurr,
> 
> I tried with tf 2.0 it failed, downgraded to 1.15 and trying now and models reppo 1.13.0. Have a feeling this will work. Will keep you posed. Do you want to work together to set this up?

i tried these but didn't work 
yes sure let's work together

**Comment by fkhjoy** [comment]
> > Hello mustafaazzurr,
> > I tried with tf 2.0 it failed, downgraded to 1.15 and trying now and models reppo 1.13.0. Have a feeling this will work. Will keep you posed. Do you want to work together to set this up?
> 
> i tried these but didn't work
> yes sure let's work together

Try with TF1.13 and model 1.13. It worked for me.

**Comment by kushallokesh** [comment]
@fkhjoy  got it to work, Thanks for the tips!!!

@mustafaazzurr Got the whole project to work, Let me know if you need help in excecution

**Comment by sean2200** [comment]
Tried TF1.13 and model 1.13. Not working. (After having tried 2.0 first) First cell in jupyter lab im getting TypeError: expected bytes, descriptor not found.

![image](https://user-images.githubusercontent.com/62683413/77607505-f03da680-6ef0-11ea-82e0-ec743b30741b.png)
![image](https://user-images.githubusercontent.com/62683413/77607405-95a44a80-6ef0-11ea-9ffe-612e05daecc3.png)

Do i need TF1.9? 
I tried TF2.0 with TF-GPU1.13 and got yet another nastier error!
Totally stuck again. 
Been probably 20+ hours in this. School project for non software engineer. Any help appreciated!

**Comment by fkhjoy** [comment]
> Tried TF1.13 and model 1.13. Not working. (After having tried 2.0 first) First cell in jupyter lab im getting TypeError: expected bytes, descriptor not found.
> 
> ![image](https://user-images.githubusercontent.com/62683413/77607505-f03da680-6ef0-11ea-82e0-ec743b30741b.png)
> ![image](https://user-images.githubusercontent.com/62683413/77607405-95a44a80-6ef0-11ea-9ffe-612e05daecc3.png)
> 
> Do i need TF1.9?
> I tried TF2.0 with TF-GPU1.13 and got yet another nastier error!
> Totally stuck again.
> Been probably 20+ hours in this. School project for non software engineer. Any help appreciated!

1. You didn't show your actual error. Please upload the bottom part. 
2. As you are working on notebook, check if you were working on the virtual environment.

**Comment by sean2200** [comment]
Thanks fkyjoy! 
1. bottom part
![image](https://user-images.githubusercontent.com/62683413/77612091-a27b6b00-6efd-11ea-9c9d-933eba75d555.png)
2. I am used to selecting from drop down, tensorflow env in anaconda and THEN opening jupyter lab. How would I know if jupyter is using my virtual env when its auto opened via prompt?
![image](https://user-images.githubusercontent.com/62683413/77612305-364d3700-6efe-11ea-925e-61080355cfe9.png)
Thanks for your time

**Comment by fkhjoy** [comment]
> Thanks fkyjoy!
> 
> 1. bottom part
>    ![image](https://user-images.githubusercontent.com/62683413/77612091-a27b6b00-6efd-11ea-9c9d-933eba75d555.png)
> 2. I am used to selecting from drop down, tensorflow env in anaconda and THEN opening jupyter lab. How would I know if jupyter is using my virtual env when its auto opened via prompt?
>    ![image](https://user-images.githubusercontent.com/62683413/77612305-364d3700-6efe-11ea-925e-61080355cfe9.png)
>    Thanks for your time

You have to set kernel as tensorflow1 instead Python3.x .
I would suggest you  to install Ipython and Jupyter Lab. Then use Jupyter Lab instead Notebook. There you can choose environment tensorflow1.
And put your models folder to this directory C:\Users\sean\Anaconda3\envs\tensorflow1\Lib\site-packages\tensorflow\
You can follow [this tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#training-the-model) .
You will not need to use jupyter notebook for training if you follow this tutorial.

**Comment by mustafaazzurr** [comment]
> Thanks fkyjoy!
> 
> 1. bottom part
>    ![image](https://user-images.githubusercontent.com/62683413/77612091-a27b6b00-6efd-11ea-9c9d-933eba75d555.png)
> 2. I am used to selecting from drop down, tensorflow env in anaconda and THEN opening jupyter lab. How would I know if jupyter is using my virtual env when its auto opened via prompt?
>    ![image](https://user-images.githubusercontent.com/62683413/77612305-364d3700-6efe-11ea-925e-61080355cfe9.png)
>    Thanks for your time

check this it worked for me and i uploaded all in on repo

https://github.com/mustafaazzurr/object_detection-with-Tensorflow-API

**Comment by sean2200** [comment]
Thank you guys! Got it
conda install tensorflow-gpu==1.15.0
NOT Pip!
Also, did NOT install tensorflow==1.13.1. 
Although, root cause to my issue has been muddied by many other things attempted. 
Could also be I used conda create -n tensorflow1 pip python=3.6 this time too.
 F**k me, root cause is truly lost. 
Bottom line was, tensorflow was not working right. Now it is.
Made tensorflow1 many times over. Deleting and starting from scratch. 
My working version uses mustafaazzurr's model as well. Thank you!
GEforce GTX 960 works perfect. 
![image](https://user-images.githubusercontent.com/62683413/77690597-ef9d2280-6f79-11ea-84f6-1ec75d389729.png)

Got object_detection_tutorial.ipyb running in jupyter notebook. 
Still running only python3 kernel. Not indicating its running tensorflow1 kernel in status 
![image](https://user-images.githubusercontent.com/62683413/77691267-f7a99200-6f7a-11ea-9157-df7a22da3c64.png)
Anyway, cycled through all cells in jupyter.
No pictures. Went in, # out line 26 27 of visualization_utils.py, pictures popped up. 
Thanks guys!
Total noob to python. Ill stick to Mech Eng. CNC and PLC and basic Visual programming. Cheers
