### ISSUE TITLE
ModuleNotFoundError: No module named 'nets'

### ISSUE THREAD

**Issue by VirenLakum** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#50]

**Comment by yangchengkang** [comment]
Hey, bro,  I also met this error when running "python train.py":
 "from nets import inception_resnet_v2
 ModuleNotFoundError: No module named 'nets'"
Have you found the solution?  I would appreciate  it if you give me some advice. Many thanks!

**Comment by VirenLakum** [comment]
I don't remember the exact reason now, i guess it happened because I didn't set the python paths properly.

**Comment by Burgomehl** [comment]
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

You need this every time you use a new console. Are add it to path.
