### ISSUE TITLE
Could not load dynamic library 'cudart64_100.dll

### ISSUE THREAD

**Issue by Kiwigamer** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#503]
It is working but on CPu instead of GPU. I install CUDNN and CUDA with the Version in the Video. 
Here the complete "Warning":

`2020-06-24 17:48:16.336891: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-06-24 17:48:16.836656: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.`

**Comment by a1684633** [comment]
You can try google "cudart64_100.dll" and download it. Then put it into tensorflow/stream_executor/platform/default dirctory.
