### ISSUE TITLE
wrong detect and only 500 step

### ISSUE THREAD

**Issue by leccyril** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#77]
hi, 

your tutorial is very helpful and great. but it does'nt work at home

-Windows 10
-tensorflow install from python 3 (v1.8)
-icore 7 16go memory
-cpu installation
-bazel ( i don't know ? )
-CUDA/cuDNN i don't know the meaning

i use this example [tutorial](https://github.com/EdjeElectronics)

i am sorry but i am novice.

what i am not understand, why only 500 step an loss very low ?
why when i scan an image with a apple watch, it detect samsung ?

my case :

i have lot of objects to detect with brand and model (iphone X , s9, smartwacth samsung or apple).

Then i will scan picture, could be nothing into to detect, could be only iphone, could be only s9, maybe both.

First i am trying with only one object. i train almost 350 picture 300 train 50 test

Is evaluate script is important because there is not in tuto ?
If we have no object t be detected in picture it have to configure negative result option ? 

when there is for example in one picture apple and S9 have i to annotate the apple ? if y want only detect the s9 ?

if i want detect both, better to annotate all in same picture when it is ?

thank you for your great help !
[tosend.zip](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/files/2139959/tosend.zip)

**Comment by leccyril** [comment]
i tried ssd_inceptionv2 and with 400 step same issue ,but with 700 steps it works

**Comment by leccyril** [comment]
i don't understant why it does'nt work

**Comment by tolotrasamuel** [comment]
What loss value do you get?

**Comment by leccyril** [comment]
<0.1 but i think it is due to the fact i test with only one object to detect....

i am trying to add outline png mask with mask rcnn detection , so i am trying with few test, if working i will increase all pictures and test...

**Comment by tolotrasamuel** [comment]
0.1 is not enough. It should be less than 0.05 consistently. Keep training
it

Tolotra Samuel Randriakotonjanahary

tolotra.com

**Comment by sauronpy** [comment]
i've achieved even less than 0.05 but its have still wrong detect.

i don't know really what i must doing...

**Comment by leccyril** [comment]
@tolotrasamuel thank it is why i thought.
@sauronpy what is the object you want to detect ? how many pictures do you use it ? how many step are you waiting ? what is the precision object to detect ? i think to detect category object it is simple but for example model in brand that not easy.

**Comment by sauronpy** [comment]
@leccyril I want to detect 4 kind of airplanes in satellite images. 125 picture for training that include 840 airplane and 25 picture for testing that include 241 airplane in it. i've reached 18000 steps.

**Comment by tolotrasamuel** [comment]
You should have at least 150 pictures per label

Tolotra Samuel Randriakotonjanahary

tolotra.com

**Comment by leccyril** [comment]
@sauronpy, yes and i will say at least 200, furthermore if airplane are very similar...

and with 125 picures 18000 step maybe it is too much, you can see tensorboard graph so see it and evaluation...

is anyone know how i can achieve it ? i want only outline mask no total segmentation.... not bounding box and no green color...
