### ISSUE TITLE
Your GPU Specs?

### ISSUE THREAD

**Issue by karanmartian** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#83]
Hi,
Any idea if you could give us what your GPU specs are? The Objection detection examples for video and webcam are running at real low Frame rate and quite a few here don't know where the bottleneck is.

**Comment by EdjeElectronics** [comment]
Hello, here's the GPU I'm using for training:
https://www.amazon.com/GeForce-Dual-fan-Gaming-Graphics-DUAL-GTX1060-O6G/dp/B01JHQT1SE/ref=sr_1_1?ie=UTF8&qid=1531542627
