### ISSUE TITLE
CPU mode

### ISSUE THREAD

**Issue by nujcharee** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#88]
Please could you provide me instruction on how to do this with CPU mode (as I dont have GPU) many thanks :)

**Comment by nujcharee** [comment]
worked now :)

**Comment by Sajjadmanal** [comment]
@nujcharee How did you solved this?

**Comment by Shaiken** [comment]
@nujcharee  hi, i need cpu mode, but i try a lot method, environment fail
i install gradation
1. python-3.5.4-amd64.exe from windows
2. Anaconda3-5.3.1-Windows-x86_64.exe from windows
3. create tensorflow1 dir to C:\
4. git tensorflow mode to C:\tensorfolw1
5. conda create -n tensorflow1 pip python=3.5
6. pip install --ignore-installed --upgrade tensorflow==1.10

other step just like author, but just set cmd => python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config... will fail
